### ISSUE TITLE
Wrong solution

### ISSUE THREAD

**Issue by binh-vu** [saebyn/linear-assignment-rust#10]
Hi,

I'm looking for a LAP solver in Rust and found your library. While testing it, I found that it returns incorrect solution for the example in Wikipedia.

The example:

```rust
let mut matrix = array![
      [8, 5, 9, 9],
      [4, 2, 6, 4],
      [7, 3, 7, 8],
];
println!(
        "{:?}",
        solver(
            &mut matrix,
            &MatrixSize {
                rows: 3,
                columns: 4
            }
        )
    );
```

It returns 15, while the output returned from the library is 16.

**Comment by saebyn** [comment]
Hi @binh-vu, thanks for opening this issue! I've been investigating it and I believe it is caused by a flaw in how this crate is handling rectangular matrices. I'll continue to work on a fix.
