### ISSUE TITLE
Build failure with recent version of rust

### ISSUE THREAD

**Issue by tvincent2** [saebyn/linear-assignment-rust#4]
Hello,

`cargo build`ing your library leads to the following error:
```
error[E0432]: unresolved import `std::collections::BitSet`
  --> src/lib.rs:29:5
   |
29 | use std::collections::BitSet;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^ no `BitSet` in `collections`
```

Indeed, `BitSet` has been moved to [its own crate](https://crates.io/crates/bit-set).

The fix is pretty easy and I could propose you a fix if you want.

Cheers,
Thomas

**Comment by saebyn** [comment]
Hey Thomas, that's be great! if you want to open a pull request, I'd be happy to review it.

-- John
