### ISSUE TITLE
Wrong assignment solution

### ISSUE THREAD

**Issue by tvincent2** [saebyn/linear-assignment-rust#6]
Hello,

I locally added the following test:

```rust
#[test]
fn solve_custom() {
    let test_matrix = na::DMatrix::from_row_slice(
        5,
        5,
        &[ 3, 6, 2, 5, 7,
            2, 3, 1, 4, 3,
            8, 1, 4, 2, 2,
            6, 3, 1, 4, 4,
            3, 2, 5, 2, 2]
    );
    let result = test_matrix.munkres();
    println!("{:?}", result);
    assert_eq!(result.len(), 5);
    let cost = result.iter().fold(0, |acc, edge| acc + test_matrix[*edge]);
    assert_eq!(cost, 10);
}
```

The expected solution is `{(0, 0), (1, 4), (2, 1), (3, 2), (4, 3)}`, giving a total cost of 10.
However, the test fails because the returned solution is `{(2, 1), (0, 2), (1, 0), (4, 3), (3, 4)}`, with a total cost of 11.

Would you have an idea why it fails?

Cheers,
Thomas

**Comment by saebyn** [comment]
Thanks for reporting this! I found the issue and I'll be merging a fix shortly
